image: docker:stable

variables:
  # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - name: docker:dind
    # https://forum.gitlab.com/t/docker-dind-stops-working-after-12-1-0-update/28664/2
    # entrypoint: ["env", "-u", "DOCKER_HOST"]
    # command: ["dockerd-entrypoint.sh"]

stages:
  - build
  - push
  - test

before_script:
  - docker info
  - export DOCKER_VERSION="$(grep DOCKER_RELEASE_VERSION Dockerfile | awk '{print $NF}')"

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build -t $CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHA .
    - docker images
    - docker run --rm $CI_COMMIT_SHORT_SHA:$CI_COMMIT_SHA docker --version

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker build -t $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:$DOCKER_VERSION -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$DOCKER_VERSION .
   - docker images
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$DOCKER_VERSION
   - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin

test_dockerhub_image:
  stage: test
  only:
   - master
  script:
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA docker --version
