---
#image: qwe1/debdocker:20.10
image: crazymax/docker:latest
services:
  - name: docker:20.10-dind
    command: ["--experimental"]
    # https://forum.gitlab.com/t/docker-dind-stops-working-after-12-1-0-update/28664/2
    # entrypoint: ["env", "-u", "DOCKER_HOST"]
    # command: ["dockerd-entrypoint.sh"]



variables:
  # for some reason docker on gitlab throws context errors with these enabled
  #DOCKER_HOST: tcp://docker:2376
  #DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  #DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  #BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.4.1/buildx-v0.4.1.linux-amd64

before_script:
  - mkdir -p $HOME/.docker/cli-plugins/
  - docker buildx version
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - "echo -e '{\n  \"experimental\": \"enabled\"\n}' | tee $HOME/.docker/config.json"
  # https://gitlab.com/richardskumat/playground/-/jobs/2762899800
  - docker context create whatever
  - docker buildx create whatever
  ##
  - docker buildx create --use --driver docker-container --name whatever --platform=linux/amd64,linux/arm/v7,linux/arm64
  - docker buildx inspect --bootstrap whatever
  - docker buildx ls
  - export DOCKER_VERSION="$(grep DOCKER_RELEASE_VERSION Dockerfile | awk '{print $NF}')"
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin


stages:
  - build
  - push
  - test

stages:
  - build
  - push
  - test

build:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    # - docker buildx build --push -t qwe1/playground:latest -t qwe1/playground:$CI_COMMIT_SHORT_SHA -f Dockerfile --platform linux/amd64,linux/arm/v7,linux/arm64 .
    - docker buildx build --load -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA  --platform linux/amd64 .
    - docker images
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA docker --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA dockerd --version

push_to_dockerhub:
 stage: push
 only:
   - master
 script:
   #- docker buildx build --push -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$DOCKER_VERSION --platform linux/amd64,linux/arm/v7,linux/arm64 .
   - docker buildx build --push -f Dockerfile -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$DOCKER_VERSION --platform linux/amd64,linux/arm64 .
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA docker --version
   - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA dockerd --version
   - docker images

test_dockerhub_image:
  stage: test
  only:
   - master
  script:
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA docker --version
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:$CI_COMMIT_SHA dockerd --version
